### ISSUE TITLE
点字表示の不具合報告

### ISSUE THREAD

**Issue by nishimotz** [nvdajp/nvdajpmiscdep#24]
私信から引用：

以下の文字列をメモ帳に貼り付けて読ませると点字表示ができないようです。
現在のベータ版を使っています。

```
リエカエリ,  聞きたかったことを隣のテーブルのお姉さまが店員に聞いてくれた。ラッキー＆ありがとうございますー 9分前,  モバツイ /
www.movatwi.jp
```

**Comment by nishimotz** [comment]
harness.py で確認：

```
.E...
======================================================================
ERROR: test_pass2 (__main__.JpBrailleTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 16, in test_pass2
    count, outfile = jpBrailleRunner.pass2()
  File "c:\work\nvda\miscDepsJp\jptools\jpBrailleRunner.py", line 116, in pass2
    t['text'], logwrite=__print, nabcc=nabcc)
  File "c:\work\nvda\miscDepsJp\source\synthDrivers\jtalk\translator2.py", line 1239, in translateWithInPos2
    outbuf, inpos2 = japanese_braille_separate(inbuf, logwrite, nabcc=nabcc)
  File "c:\work\nvda\miscDepsJp\source\synthDrivers\jtalk\translator2.py", line 928, in japanese_braille_separate
    li = mecab_to_morphs(mf)
  File "c:\work\nvda\miscDepsJp\source\synthDrivers\jtalk\translator2.py", line 202, in mecab_to_morphs
    update_phonetic_symbols(mo)
  File "c:\work\nvda\miscDepsJp\source\synthDrivers\jtalk\translator2.py", line 159, in update_phonetic_symbols
    if mo.yomi[p] == '繝ｼ' and mo.kana[p] in '繧｢繧､繧ｨ繧ｪ':
IndexError: string index out of range
```
